title: Mandela efekt
baseURL: https://xenodochial-lewin-dc7bbf.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics : UA-139390205-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Na této stránce se dozvíte více o fenoménu známém jako Mandela efekt, který sice nebyl nikdy vědecky doložený, ale velké množství lidí ho po celém světě zažilo.
  authors: Eliška, Dominika, Pepa

